### Step 0
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`

Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.

Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

In [1]:
import pandas as pd
import numpy as np

In [2]:
column_names_for_Energy= ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']

In [3]:
# Energy= pd.read_csv(r'data\indicators.csv', names=column_names_for_Energy )
Energy= pd.read_excel(r'data\Energy Indicators.xls', names=column_names_for_Energy, skiprows= 17, skipfooter= 38)
Energy=Energy.reset_index(drop=True)

In [4]:
display(Energy)

Country Energy Supply Energy Supply per Capita  \
0                  Afghanistan           321                       10   
1                      Albania           102                       35   
2                      Algeria          1959                       51   
3               American Samoa           ...                      ...   
4                      Andorra             9                      121   
..                         ...           ...                      ...   
222                   Viet Nam          2554                       28   
223  Wallis and Futuna Islands             0                       26   
224                      Yemen           344                       13   
225                     Zambia           400                       26   
226                   Zimbabwe           480                       32   

     % Renewable  
0      78.669280  
1     100.000000  
2       0.551010  
3       0.641026  
4      88.695650  
..           ...  
222    45.321520  
223     0.000000  
224     0.000000  
225    99.714670  
226    52.536120  

[227 rows x 4 columns]

In [5]:
Energy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Country                   227 non-null    object 
 1   Energy Supply             227 non-null    object 
 2   Energy Supply per Capita  227 non-null    object 
 3   % Renewable               227 non-null    float64
dtypes: float64(1), object(3)
memory usage: 7.2+ KB


In [6]:
Energy.rename(columns={'Energy Supply':'Energy_Supply','Energy Supply per Capita':'Energy_Supply_per_Capita','% Renewable':'Renewable%'}, inplace=True)

In [7]:
def keep_number(s):
    s2 = ''.join([i for i in s if i.isdigit()])
    return s2

In [8]:
def remove_digits(s):
    new_string = ''
    for character in s:
        if not character.isdigit():
            new_string += character
    return new_string

In [9]:
def remove_brackets(s):
    new_string = ''
    for i in s:
        if i == '(':
            new_string= s[:s.index('(')] + s[s.index(')')+1:]
            return new_string
    return s

In [10]:
Energy['Energy_Supply'],Energy['Energy_Supply_per_Capita']= Energy['Energy_Supply'].astype(str),Energy['Energy_Supply_per_Capita'].astype(str)

In [11]:
Energy['Energy_Supply']=Energy['Energy_Supply'].apply(keep_number)
Energy['Energy_Supply_per_Capita']=Energy['Energy_Supply_per_Capita'].apply(keep_number)
Energy['Country']=Energy['Country'].apply(remove_digits)
Energy['Country']=Energy['Country'].apply(remove_brackets)
Energy['Energy_Supply_per_Capita']=Energy['Energy_Supply_per_Capita'].apply(keep_number)

In [12]:
Energy['Energy_Supply']= pd.to_numeric(Energy['Energy_Supply'])
Energy['Energy_Supply_per_Capita']= pd.to_numeric(Energy['Energy_Supply_per_Capita'])

In [13]:
Energy['Energy_Supply']=Energy['Energy_Supply']*1000000

<!-- Rename the following list of countries (for use in later questions):

"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong" -->

In [14]:
# "Republic of Korea": "South Korea",
# "United States of America": "United States",
# "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
# "China, Hong Kong Special Administrative Region": "Hong Kong"
Energy.Country = Energy.Country.replace({'Republic of Korea': 'South Korea', 'United States of America': 'United States'})
Energy.Country = Energy.Country.replace({'United Kingdom of Great Britain and Northern Ireland': 'United Kingdom'})
Energy['Country'] = Energy['Country'].apply(lambda x: 'Hong Kong' if x.startswith('China') else x)


In [15]:
display(Energy)

Country  Energy_Supply  Energy_Supply_per_Capita  \
0                  Afghanistan   3.210000e+08                      10.0   
1                      Albania   1.020000e+08                      35.0   
2                      Algeria   1.959000e+09                      51.0   
3               American Samoa            NaN                       NaN   
4                      Andorra   9.000000e+06                     121.0   
..                         ...            ...                       ...   
222                   Viet Nam   2.554000e+09                      28.0   
223  Wallis and Futuna Islands   0.000000e+00                      26.0   
224                      Yemen   3.440000e+08                      13.0   
225                     Zambia   4.000000e+08                      26.0   
226                   Zimbabwe   4.800000e+08                      32.0   

     Renewable%  
0     78.669280  
1    100.000000  
2      0.551010  
3      0.641026  
4     88.695650  
..          ...  
222   45.321520  
223    0.000000  
224    0.000000  
225   99.714670  
226   52.536120  

[227 rows x 4 columns]

### Step 1
<br>

Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```

<br>

In [16]:
GDP= pd.read_csv(r'data\world_bank.csv', skiprows=3, header=1)

In [17]:
GDP.rename(columns= {'Country Name':'Country_name', 'Country Code':'Country_Code', 'Indicator Name':'Indicator_name', 'Indicator Code':'Indicator_Code' }, inplace=True)

In [18]:
display(GDP.head(2))

Country_name Country_Code                            Indicator_name  \
0        Aruba          ABW  GDP at market prices (constant 2010 US$)   
1      Andorra          AND  GDP at market prices (constant 2010 US$)   

   Indicator_Code  1960  1961  1962  1963  1964  1965  ...          2006  \
0  NY.GDP.MKTP.KD   NaN   NaN   NaN   NaN   NaN   NaN  ...           NaN   
1  NY.GDP.MKTP.KD   NaN   NaN   NaN   NaN   NaN   NaN  ...  4.018196e+09   

           2007          2008          2009          2010          2011  \
0           NaN           NaN           NaN  2.467704e+09           NaN   
1  4.021331e+09  3.675728e+09  3.535389e+09  3.346317e+09  3.185605e+09   

           2012          2013  2014  2015  
0           NaN           NaN   NaN   NaN  
1  3.129538e+09  3.127550e+09   NaN   NaN  

[2 rows x 60 columns]

In [19]:
GDP.Country_name = GDP.Country_name.replace({"Korea, Rep.": "South Korea", "Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"})

### Step 2
Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

In [20]:
ScimEn= pd.read_excel(r'data\scimagojr-3.xlsx')

### Step 3
Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This step should yeild a DataFrame with 20 columns and 15 entries.*

In [21]:
ScimEn_top_ten=ScimEn.head(15)

In [51]:
ScimEn

Rank             Country  Documents  Citable documents  Citations  \
0       1               China     127050             126767     597237   
1       2       United States      96661              94747     792274   
2       3               Japan      30504              30287     223024   
3       4      United Kingdom      20944              20357     206091   
4       5  Russian Federation      18534              18301      34266   
..    ...                 ...        ...                ...        ...   
186   187              Guyana          1                  1          0   
187   188    Christmas Island          1                  1          0   
188   189             Reunion          1                  1          2   
189   190         Saint Lucia          1                  1          0   
190   191          Mauritania          1                  1          1   

     Self-citations  Citations per document  H index  
0            411683                    4.70      138  
1            265436                    8.20      230  
2             61554                    7.31      134  
3             37874                    9.84      139  
4             12422                    1.85       57  
..              ...                     ...      ...  
186               0                    0.00        0  
187               0                    0.00        0  
188               1                    2.00        1  
189               0                    0.00        0  
190               0                    1.00        1  

[191 rows x 8 columns]

In [22]:
Merge1 = pd.merge(ScimEn_top_ten,Energy , how='left', on='Country')
Merged = pd.merge(Merge1,GDP[['Country_name', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']], how= 'inner', left_on= 'Country', right_on= 'Country_name')

In [23]:
Merged=Merged.set_index('Country')

In [24]:
display(Merged)

Rank  Documents  Citable documents  Citations  \
Country                                                             
China                  1     127050             126767     597237   
United States          2      96661              94747     792274   
Japan                  3      30504              30287     223024   
United Kingdom         4      20944              20357     206091   
Russian Federation     5      18534              18301      34266   
Canada                 6      17899              17620     215003   
Germany                7      17027              16831     140566   
India                  8      15005              14841     128763   
France                 9      13153              12973     130632   
South Korea           10      11983              11923     114675   
Italy                 11      10964              10794     111850   
Spain                 12       9428               9330     123336   
Iran                  13       8896               8819      57470   
Australia             14       8831               8725      90765   
Brazil                15       8668               8596      60702   

                    Self-citations  Citations per document  H index  \
Country                                                               
China                       411683                    4.70      138   
United States               265436                    8.20      230   
Japan                        61554                    7.31      134   
United Kingdom               37874                    9.84      139   
Russian Federation           12422                    1.85       57   
Canada                       40930                   12.01      149   
Germany                      27426                    8.26      126   
India                        37209                    8.58      115   
France                       28601                    9.93      114   
South Korea                  22595                    9.57      104   
Italy                        26661                   10.20      106   
Spain                        23964                   13.08      115   
Iran                         19125                    6.46       72   
Australia                    15606                   10.28      107   
Brazil                       14396                    7.00       86   

                    Energy_Supply  Energy_Supply_per_Capita  Renewable%  ...  \
Country                                                                  ...   
China                         NaN                       NaN         NaN  ...   
United States        9.083800e+10                     286.0   11.570980  ...   
Japan                1.898400e+10                     149.0   10.232820  ...   
United Kingdom       7.920000e+09                     124.0   10.600470  ...   
Russian Federation   3.070900e+10                     214.0   17.288680  ...   
Canada               1.043100e+10                     296.0   61.945430  ...   
Germany              1.326100e+10                     165.0   17.901530  ...   
India                3.319500e+10                      26.0   14.969080  ...   
France               1.059700e+10                     166.0   17.020280  ...   
South Korea          1.100700e+10                     221.0    2.279353  ...   
Italy                6.530000e+09                     109.0   33.667230  ...   
Spain                4.923000e+09                     106.0   37.968590  ...   
Iran                          NaN                       NaN         NaN  ...   
Australia            5.386000e+09                     231.0   11.810810  ...   
Brazil               1.214900e+10                      59.0   69.648030  ...   

                            2006          2007          2008          2009  \
Country                                                                      
China               3.992331e+12  4.559041e+12  4.997775e+12  5.459247e+12   
United States       1.479230e+13  1.505540e

In [25]:
Merged.shape

(15, 21)

In [26]:
Merged.columns

Index(['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy_Supply',
       'Energy_Supply_per_Capita', 'Renewable%', 'Country_name', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015'],
      dtype='object')

In [27]:
Merged=Merged.drop('Country_name', axis=1)

In [28]:
Merged.shape

(15, 20)

### Step 4
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This step should yield a single number.*

In [29]:
print (f'ScimEn yields {ScimEn.shape[0]} rows and with just 15 top entries: {ScimEn.shape[0]} - {Merged.shape[0]} = {ScimEn.shape[0] - Merged.shape[0]} entires were lost')

ScimEn yields 191 rows and with just 15 top entries: 191 - 15 = 176 entires were lost


ScimEn yields 191 rows and with just 15 top entries: 191-15=  176 entires were lost

### Step 5

#### Answer the following questions in the context of only the top 15 countries by Scimagojr Rank 


What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This step should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*

In [30]:
Merged.head()

Rank  Documents  Citable documents  Citations  \
Country                                                             
China                  1     127050             126767     597237   
United States          2      96661              94747     792274   
Japan                  3      30504              30287     223024   
United Kingdom         4      20944              20357     206091   
Russian Federation     5      18534              18301      34266   

                    Self-citations  Citations per document  H index  \
Country                                                               
China                       411683                    4.70      138   
United States               265436                    8.20      230   
Japan                        61554                    7.31      134   
United Kingdom               37874                    9.84      139   
Russian Federation           12422                    1.85       57   

                    Energy_Supply  Energy_Supply_per_Capita  Renewable%  \
Country                                                                   
China                         NaN                       NaN         NaN   
United States        9.083800e+10                     286.0    11.57098   
Japan                1.898400e+10                     149.0    10.23282   
United Kingdom       7.920000e+09                     124.0    10.60047   
Russian Federation   3.070900e+10                     214.0    17.28868   

                            2006          2007          2008          2009  \
Country                                                                      
China               3.992331e+12  4.559041e+12  4.997775e+12  5.459247e+12   
United States       1.479230e+13  1.505540e+13  1.501149e+13  1.459484e+13   
Japan               5.496542e+12  5.617036e+12  5.558527e+12  5.251308e+12   
United Kingdom      2.419631e+12  2.482203e+12  2.470614e+12  2.367048e+12   
Russian Federation  1.385793e+12  1.504071e+12  1.583004e+12  1.459199e+12   

                            2010          2011          2012          2013  \
Country                                                                      
China               6.039659e+12  6.612490e+12  7.124978e+12  7.672448e+12   
United States       1.496437e+13  1.520402e+13  1.554216e+13  1.577367e+13   
Japan               5.498718e+12  5.473738e+12  5.569102e+12  5.644659e+12   
United Kingdom      2.403504e+12  2.450911e+12  2.479809e+12  2.533370e+12   
Russian Federation  1.524917e+12  1.589943e+12  1.645876e+12  1.666934e+12   

                            2014          2015  
Country                                         
China               8.230121e+12  8.797999e+12  
United States       1.615662e+13  1.654857e+13  
Japan               5.642884e+12  5.669563e+12  
United Kingdom      2.605643e+12  2.666333e+12  
Russian Federation  1.678709e+12  1.616149e+12

In [31]:
avgGDP= pd.Series(Merged.iloc[:,10:].sum(axis=1))

In [32]:
type(avgGDP)

pandas.core.series.Series

In [33]:
avgGDP

Country
China                 6.348609e+13
United States         1.536434e+14
Japan                 5.542208e+13
United Kingdom        2.487907e+13
Russian Federation    1.565459e+13
Canada                1.660647e+13
Germany               3.493025e+13
India                 1.769297e+13
France                2.681725e+13
South Korea           1.106715e+13
Italy                 2.120175e+13
Spain                 1.418078e+13
Iran                  3.997402e+12
Australia             1.164043e+13
Brazil                2.189794e+13
dtype: float64

### Step  6
What is the mean `Energy Supply per Capita`?

*This step should return a single number.*

In [34]:
Merged.Energy_Supply_per_Capita.mean()

165.53846153846155

### Step 7
What country has the maximum % Renewable and what is the percentage?

*This step should return a tuple with the name of the country and the percentage.*

In [35]:
#there must be a better way
tuple_7=(Merged.index[int(Merged['Rank'][Merged['Renewable%'] == Merged['Renewable%'].max()]-1)],Merged['Renewable%'].max())

In [36]:
tuple_7

('Brazil', 69.64803)

### Step 8
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This step should return a tuple with the name of the country and the ratio.*

In [37]:
Merged.columns

Index(['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy_Supply',
       'Energy_Supply_per_Capita', 'Renewable%', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'],
      dtype='object')

In [38]:
Merged['Ratio']= Merged['Self-citations']/Merged['Citations']

In [39]:
# same stupid code from above
tuple_8=(Merged.Ratio.max(),
        Merged.index[int(Merged['Rank'][Merged['Ratio'] == Merged.Ratio.max()]-1)])
tuple_8

(0.6893126179389422, 'China')

### Step 9
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This step should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*

In [40]:
Merged['HighRenew']= Merged['Renewable%'].apply(lambda x:1 if (Merged['Renewable%'].median() <= x) else 0)
type(Merged['HighRenew'])

pandas.core.series.Series

In [41]:
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}

### Step 10
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*

In [42]:
type(ContinentDict.values())

dict_values

In [43]:
Continents=pd.Series(list(ContinentDict.values()), index=ContinentDict.keys(), name= 'Continents')

In [44]:
Merged= Merged.merge(Continents, left_index=True, right_index= True)

In [45]:
Merged.insert(0, 'Continents', Merged.pop('Continents'))

In [46]:
Merged.columns

Index(['Continents', 'Rank', 'Documents', 'Citable documents', 'Citations',
       'Self-citations', 'Citations per document', 'H index', 'Energy_Supply',
       'Energy_Supply_per_Capita', 'Renewable%', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', 'Ratio',
       'HighRenew'],
      dtype='object')

In [47]:
Merged['estimated_population']= Merged.Energy_Supply/Merged.Energy_Supply_per_Capita

In [48]:
Merged['estimated_population']

China                          NaN
United States         3.176154e+08
Japan                 1.274094e+08
United Kingdom        6.387097e+07
Russian Federation    1.435000e+08
Canada                3.523986e+07
Germany               8.036970e+07
India                 1.276731e+09
France                6.383735e+07
South Korea           4.980543e+07
Italy                 5.990826e+07
Spain                 4.644340e+07
Iran                           NaN
Australia             2.331602e+07
Brazil                2.059153e+08
Name: estimated_population, dtype: float64

In [49]:
step10= Merged.groupby('Continents')['estimated_population'].agg(['size','sum','mean','std'])

In [50]:
step10

size           sum          mean           std
Continents                                                   
Asia              5  1.453946e+09  4.846485e+08  6.870599e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN